Repository devruso/soulpet-back, pull requests merged in 2023-04, with the labels that each got.

#22 Model produto finalizado
  database/produto.js
Labels: documentation

#25 Post produto finalizado
  database/produto.js
  index.js
  routes/produtos.js
Labels: documentation

#26 Get produtos finalizado
  routes/produtos.js
Labels: documentation

#31 Post dos pedidos
  routes/pedidos.js
Labels: documentation, enhancement

#32 delete pedidos
  routes/pedidos.js
Labels: documentation, enhancement

#33 Listagem de pets por cliente
  routes/pets.js
Labels: documentation

#34 Correção de validação get
  routes/produtos.js
Labels: enhancement

#38 Correção rotas put e delete
  routes/produtos.js
Labels: enhancement

#39 Rota PUT Produtos
  routes/produtos.js
Labels: enhancement

#40 Rota DELETE Produtos
  routes/produtos.js
Labels: enhancement

#41 Rota Post serviço
  .env.example
  database/servico.js
  index.js
  routes/servicos.js
Labels: enhancement

#43 Correção ENV
  .env.example
Labels: duplicate

#47 Correcao
  routes/pedidos.js
Labels: duplicate

#49 Rotas Deletar servicos
  routes/servicos.js
Labels: enhancement

#51 correção lista produtos
  routes/produtos.js
Labels: duplicate

#52 Correcoes em Pedidos
  database/pedido.js
  index.js
  routes/pedidos.js
Labels: duplicate

#53 adicao de rota post e correcao em agendamento
  database/agendamento.js
  index.js
  routes/agendamentos.js
Labels: enhancement

#54 PUT de serviços
  routes/servicos.js
Labels: enhancement
