Repository devruso/soulpet-back, pull requests merged in 2023-05, with the labels that each got.

#55 Relatorio pdf clientes
  index.js
  package-lock.json
  package.json
  routes/clientespdf.js
Labels: enhancement

#58 Listagem de Servicos
  routes/servicos.js
Labels: enhancement

#61 correcao
  routes/servicos.js
Labels: enhancement

#62 Rota de listar agendamentos
  database/agendamento.js
  index.js
  routes/agendamentos.js
Labels: documentation, enhancement

#63 Rota GET que mostra o endereço que pertence a um Cliente
  routes/clientes.js
Labels: enhancement

#64 Deletar Agendamentos
  routes/agendamentos.js
Labels: enhancement

#68 PUT para atualizar um agendamento
  routes/agendamentos.js
Labels: enhancement

#69 correcao da relacao de relacionamento
  database/agendamento.js
  database/associacao.js
Labels: duplicate

#70 Página informações do cliente
  routes/clientes.js
Labels: enhancement

#72 Melhorias no initiateDB
  database/agendamento.js
  database/initiateDB.js
Labels: enhancement

#73 correcao uuid com require
  database/initiateDB.js
Labels: duplicate

#75 Paginação pet back
  routes/pets.js
Labels: enhancement

#76 Readme e License back-end
  LICENSE.md
  README.md
Labels: enhancement

#78 Be 10 2
  routes/servicos.js
Labels: duplicate

#83 correcao em pedidos
  database/pedido.js
Labels: duplicate

#86 remocao conexao DB via index
  index.js
Labels: duplicate

#87 correcao conexao com mongoose
  index.js
  logMongo.js
Labels: duplicate

#88 correção POST Agendamentos
  routes/agendamentos.js
Labels: duplicate

#89 remocao de dado desnecessario em post agendamento
  routes/agendamentos.js
Labels: duplicate
